"""
Django settings for exemplo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)(t+s8-)yh9=lq@ayxaf6wq)v16p+lc4)hhtpn*^innwsc=)7+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000',
    'https://localhost:8000',
    'https://cautious-enigma-76rxwrgqv5g3rr7v-8080.app.github.dev',
]

LOGIN_URL = 'sec-login'
LOGOUT_URL = 'home'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #incluidos
    'contatos',
    'exemplo',
    'exemplos', #apenas um exemplo de backend
    'rest_framework',
    'corsheaders',
    'carros',
    'drf_yasg',
    'coreapi',
    'accounts',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #para usar o CORS
]

ROOT_URLCONF = "exemplo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "exemplo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    "DBMTCars": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, 'mtcars.sqlite3'),
    }
}

DATABASE_ROUTERS = [
    #carros: nome da aplicação (diretório)
    #db_routers: nome do arquivo (sem .py)
    #DBRouter: nome da classe
    'carros.db_routers.DBRouter'
]

# Para permitir CORS
CORS_ORIGIN_WHITELIST = [
    'https://cautious-enigma-76rxwrgqv5g3rr7v-8080.app.github.dev',
    # Adicione outras origens permitidas, se necessário
]

CORS_ALLOW_ALL_ORIGINS = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-BR"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

DATE_INPUT_FORMATS = ['%d/%m/%Y', '%Y-%m-%d']  #formatos aceitos

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#configuração do email para redefinição de senha
# Option 1: File-based (saves emails to files)
# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

# Option 2: Gmail SMTP (sends real emails)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'  # Replace with your Gmail
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Use App Password, not regular password

"""For Gmail SMTP:

If you're using Gmail (which is commented out in your settings), EMAIL_HOST_PASSWORD should be an App Password, not your regular Gmail password. Here's why:

    App Passwords are special passwords generated by Google for applications
    They're more secure than using your regular password
    They're required when you have 2-factor authentication enabled

How to get a Gmail App Password:

    Go to your Google Account settings
    Navigate to Security → 2-Step Verification
    Scroll down to "App passwords"
    Generate a new app password for "Mail"
    Use that 16-character password as your EMAIL_HOST_PASSWORD
"""

# Option 3: Console (current - prints to terminal)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#DEFAULT_FROM_EMAIL = 'webmaster@localhost'

#CONFIGURAÇÕES PARA O SWAGGER
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}